apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: false
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - mountPath: /var/cache/nginx
          name: cache-volume
        - mountPath: /var/run
          name: run-volume
        - mountPath: /tmp
          name: tmp-volume
        - mountPath: /var/log/nginx
          name: log-volume
  volumes:
    - name: cache-volume
      emptyDir: {}
    - name: run-volume
      emptyDir: {}
    - name: tmp-volume
      emptyDir: {}
    - name: log-volume
      emptyDir: {}